# -*- coding: utf-8 -*-
"""DecisionTreeOrchid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AFoWJXZkFc5Iglb2Xq5e4LCdMoHuYlH0
"""

import numpy as np
import pandas as pd
from sklearn import tree

irisDataset = pd.read_csv('Orchid.csv', delimiter=';', header=0)

irisDataset.head()

irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

irisDataset = irisDataset.drop(labels="Id", axis=1)

print(irisDataset)

irisDataset = irisDataset.to_numpy()

print(irisDataset)

dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]),
                             axis=0)

print(dataTraining)
len(dataTraining)

inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

model = tree.DecisionTreeClassifier()

model = model.fit(inputTraining, labelTraining)

hasilPredik = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Label Prediksi : ", hasilPredik)

#menghitung akurasi
predBenar = (hasilPredik == labelTesting).sum()
predSalah = (hasilPredik != labelTesting).sum()
print("Prediksi Benar :", predBenar, "data")
print("Prediksi Salah :", predSalah, "data")
print("Akurasi :", predBenar/(predBenar+predSalah) * 100, "%")